<a href="https://colab.research.google.com/github/sushrutha777/Air-Canvas/blob/master/WordEmbeding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
from tensorflow.keras.preprocessing.text import one_hot

In [55]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [56]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [57]:
## Define the vocabulary size
voc_size=10000

In [58]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [59]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2388, 8506, 3450, 4001],
 [2388, 8506, 3450, 2012],
 [2388, 8337, 3450, 2717],
 [3989, 5908, 740, 138, 7827],
 [3989, 5908, 740, 138, 5627],
 [8436, 2388, 5838, 3450, 4167],
 [4791, 8914, 1162, 138]]

In [60]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [61]:
import numpy as np

In [62]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2388 8506 3450 4001]
 [   0    0    0    0 2388 8506 3450 2012]
 [   0    0    0    0 2388 8337 3450 2717]
 [   0    0    0 3989 5908  740  138 7827]
 [   0    0    0 3989 5908  740  138 5627]
 [   0    0    0 8436 2388 5838 3450 4167]
 [   0    0    0    0 4791 8914 1162  138]]


In [63]:
## feature representation
dim=10

In [64]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_shape=(sent_length,)))
model.compile(optimizer='adam', loss='mse')
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [65]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


array([[[-0.01463634,  0.00479989,  0.02698393,  0.02309115,
         -0.03952813, -0.02088282,  0.03387152,  0.01702814,
         -0.00470165,  0.02613332],
        [-0.01463634,  0.00479989,  0.02698393,  0.02309115,
         -0.03952813, -0.02088282,  0.03387152,  0.01702814,
         -0.00470165,  0.02613332],
        [-0.01463634,  0.00479989,  0.02698393,  0.02309115,
         -0.03952813, -0.02088282,  0.03387152,  0.01702814,
         -0.00470165,  0.02613332],
        [-0.01463634,  0.00479989,  0.02698393,  0.02309115,
         -0.03952813, -0.02088282,  0.03387152,  0.01702814,
         -0.00470165,  0.02613332],
        [-0.02983034,  0.00588813, -0.03625512,  0.04254034,
         -0.02430488, -0.03215187,  0.02785594, -0.01112236,
          0.0131811 ,  0.02978763],
        [-0.00719164, -0.03969673,  0.01094263, -0.03540716,
          0.04231877,  0.00435502, -0.03097522,  0.02979254,
         -0.01997808, -0.02315433],
        [ 0.04895646, -0.02327743,  0.0257608 ,  0.0

In [67]:
model.predict(embedded_docs[0].reshape(1,-1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


array([[[-0.01463634,  0.00479989,  0.02698393,  0.02309115,
         -0.03952813, -0.02088282,  0.03387152,  0.01702814,
         -0.00470165,  0.02613332],
        [-0.01463634,  0.00479989,  0.02698393,  0.02309115,
         -0.03952813, -0.02088282,  0.03387152,  0.01702814,
         -0.00470165,  0.02613332],
        [-0.01463634,  0.00479989,  0.02698393,  0.02309115,
         -0.03952813, -0.02088282,  0.03387152,  0.01702814,
         -0.00470165,  0.02613332],
        [-0.01463634,  0.00479989,  0.02698393,  0.02309115,
         -0.03952813, -0.02088282,  0.03387152,  0.01702814,
         -0.00470165,  0.02613332],
        [-0.02983034,  0.00588813, -0.03625512,  0.04254034,
         -0.02430488, -0.03215187,  0.02785594, -0.01112236,
          0.0131811 ,  0.02978763],
        [-0.00719164, -0.03969673,  0.01094263, -0.03540716,
          0.04231877,  0.00435502, -0.03097522,  0.02979254,
         -0.01997808, -0.02315433],
        [ 0.04895646, -0.02327743,  0.0257608 ,  0.0